//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lf_crm_db2Entities : DbContext
    {
        public lf_crm_db2Entities()
            : base("name=lf_crm_db2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bas_dict> bas_dict { get; set; }
        public virtual DbSet<cst_activity> cst_activity { get; set; }
        public virtual DbSet<cst_customer> cst_customer { get; set; }
        public virtual DbSet<cst_linkman> cst_linkman { get; set; }
        public virtual DbSet<cst_lost> cst_lost { get; set; }
        public virtual DbSet<cst_service> cst_service { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_line> orders_line { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sal_chance> sal_chance { get; set; }
        public virtual DbSet<sal_plan> sal_plan { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<sys_right> sys_right { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_role_right> sys_role_right { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
    }
}
