//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cst_lost
    {
        public int lst_id { get; set; }
        public string lst_cust_no { get; set; }
        public string lst_cust_name { get; set; }
        public int lst_cust_manager_id { get; set; }
        public string lst_cust_manager_name { get; set; }
        public Nullable<System.DateTime> lst_last_order_date { get; set; }
        public Nullable<System.DateTime> lst_lost_date { get; set; }
        public string lst_delay { get; set; }
        public string lst_reason { get; set; }
        public Nullable<int> lst_status { get; set; }
    
        public virtual cst_customer cst_customer { get; set; }
    }
}
