//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cst_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cst_customer()
        {
            this.cst_activity = new HashSet<cst_activity>();
            this.cst_linkman = new HashSet<cst_linkman>();
            this.cst_lost = new HashSet<cst_lost>();
            this.orders = new HashSet<orders>();
            this.cst_service = new HashSet<cst_service>();
        }
    
        public int cust_Id { get; set; }
        public string cust_no { get; set; }
        public string cust_name { get; set; }
        public string cust_region { get; set; }
        public Nullable<int> cust_manager_id { get; set; }
        public string cust_manager_name { get; set; }
        public Nullable<int> cust_level { get; set; }
        public string cust_level_label { get; set; }
        public Nullable<int> cust_satisfy { get; set; }
        public Nullable<int> cust_credit { get; set; }
        public string cust_addr { get; set; }
        public string cust_zip { get; set; }
        public string cust_tel { get; set; }
        public string cust_fax { get; set; }
        public string cust_website { get; set; }
        public string cust_licence_no { get; set; }
        public string cust_chieftain { get; set; }
        public Nullable<int> cust_bankroll { get; set; }
        public Nullable<int> cust_turnover { get; set; }
        public string cust_bank { get; set; }
        public string cust_bank_account { get; set; }
        public string cust_local_tax_no { get; set; }
        public string cust_national_tax_no { get; set; }
        public string cust_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cst_activity> cst_activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cst_linkman> cst_linkman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cst_lost> cst_lost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cst_service> cst_service { get; set; }
    }
}
