//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cst_linkman
    {
        public int lkm_id { get; set; }
        public string lkm_cust_no { get; set; }
        public string lkm_cust_name { get; set; }
        public string lkm_name { get; set; }
        public string lkm_sex { get; set; }
        public string lkm_postion { get; set; }
        public string lkm_tel { get; set; }
        public string lkm_mobile { get; set; }
        public string lkm_memo { get; set; }
    
        public virtual cst_customer cst_customer { get; set; }
    }
}
