//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cst_service
    {
        public int svr_id { get; set; }
        public string svr_type { get; set; }
        public string svr_title { get; set; }
        public string svr_cust_no { get; set; }
        public string svr_cust_name { get; set; }
        public string svr_status { get; set; }
        public string svr_request { get; set; }
        public int svr_create_id { get; set; }
        public string svr_create_by { get; set; }
        public Nullable<System.DateTime> svr_create_date { get; set; }
        public Nullable<int> svr_due_id { get; set; }
        public string svr_due_to { get; set; }
        public Nullable<System.DateTime> svr_due_date { get; set; }
        public string svr_deal { get; set; }
        public Nullable<int> svr_deal_id { get; set; }
        public string svr_deal_by { get; set; }
        public Nullable<System.DateTime> svr_deal_date { get; set; }
        public string svr_result { get; set; }
        public Nullable<int> svr_satisfy { get; set; }
    
        public virtual cst_customer cst_customer { get; set; }
    }
}
