//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_line
    {
        public int odd_id { get; set; }
        public int odd_order_id { get; set; }
        public int odd_prod_id { get; set; }
        public int odd_count { get; set; }
        public string odd_unit { get; set; }
        public Nullable<decimal> odd_price { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
