//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_chance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sal_chance()
        {
            this.sal_plan = new HashSet<sal_plan>();
        }
    
        public int chc_id { get; set; }
        public string chc_source { get; set; }
        public string chc_cust_name { get; set; }
        public string chc_title { get; set; }
        public int chc_rate { get; set; }
        public string chc_linkman { get; set; }
        public string chc_tel { get; set; }
        public string chc_desc { get; set; }
        public int chc_create_id { get; set; }
        public string chc_create_by { get; set; }
        public Nullable<System.DateTime> chc_create_date { get; set; }
        public Nullable<int> chc_due_id { get; set; }
        public string chc_due_to { get; set; }
        public Nullable<System.DateTime> chc_due_date { get; set; }
        public int chc_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sal_plan> sal_plan { get; set; }
    }
}
