//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public int usr_id { get; set; }
        public string usr_name { get; set; }
        public string usr_pwd { get; set; }
        public int usr_role_id { get; set; }
        public int usr_state { get; set; }
    
        public virtual sys_role sys_role { get; set; }
    }
}
